# Generated by Django 5.0.7 on 2024-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='stock_level',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Removal', 'Removal'), ('Update', 'Update')], max_length=10),
        ),
    ]
