# Generated by Django 5.0.7 on 2024-08-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_stock_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity_produced', models.PositiveIntegerField()),
                ('production_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('raw_materials', models.ManyToManyField(through='inventory.ProductionMaterial', to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='production_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productionrecord'),
        ),
    ]
