# Generated by Django 5.0.7 on 2024-08-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productionmaterial_productionrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
