# Generated by Django 5.0.7 on 2024-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productionrecord_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='production_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
