# Generated by Django 5.0.7 on 2024-08-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productionrecord_production_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='raw_materials',
        ),
        migrations.DeleteModel(
            name='ProductionMaterial',
        ),
        migrations.DeleteModel(
            name='ProductionRecord',
        ),
    ]
