# Generated by Django 5.0.7 on 2024-08-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_productionrecord_raw_materials_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productID", models.CharField(max_length=100)),
                ("rawMaterialID", models.CharField(max_length=100)),
                ("quantityProduced", models.PositiveIntegerField()),
                ("quantityUsed", models.PositiveIntegerField()),
                ("productionDate", models.DateField()),
            ],
        ),
    ]
