# Generated by Django 5.0.7 on 2024-08-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='rawMaterialID',
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='productName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='rawMaterialName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
