# Generated by Django 5.0.7 on 2024-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_productionrecord_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='productionDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
