# Generated by Django 5.0.7 on 2024-08-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_productionrecord_productiondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Addition', 'Addition'), ('Update', 'Update')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productionrecord')),
            ],
        ),
    ]
