# Generated by Django 5.0.7 on 2024-08-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_productiontransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionrecord",
            name="rawMaterialName",
        ),
        migrations.AddField(
            model_name="productionrecord",
            name="rawMaterials",
            field=models.ManyToManyField(
                related_name="production_records", to="inventory.inventoryitem"
            ),
        ),
    ]
