# Generated by Django 5.0.7 on 2024-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_remove_productionrecord_rawmaterialname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionrecord",
            name="rawMaterials",
            field=models.ManyToManyField(
                blank=True,
                related_name="production_records",
                to="inventory.inventoryitem",
            ),
        ),
    ]
