# Generated by Django 5.0.7 on 2024-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_productionrecord_rawmaterials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionrecord",
            name="quantityUsed",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
