# Generated by Django 5.0.7 on 2024-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_productionrecord_quantityused'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontransaction',
            name='quantityUsed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productiontransaction',
            name='rawMaterials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
