# Generated by Django 5.0.7 on 2024-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productiontransaction_quantityused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
