# Generated by Django 5.0.7 on 2024-08-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productionrecord_unit_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionTransaction',
        ),
    ]
