# Generated by Django 5.0.7 on 2024-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_delete_productiontransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='productionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
